### ISSUE TITLE
Where should the "Chat" link be redirected?

### ISSUE THREAD

**Issue by gotham3** [python-gsoc/python-gsoc.github.io#101]
<img width="884" alt="Screenshot (49)" src="https://user-images.githubusercontent.com/29517118/71808728-91f0ec80-3094-11ea-83f0-df463d79171c.png">

**Comment by GatienC** [comment]
I think it should be redirecting to the irc channel. When you inspect the element, there is a href=#python-gsoc. Perhaps it should be https://webchat.freenode.net/#python-gsoc .

**Comment by gotham3** [comment]
Yeah you're prolly right!
