### ISSUE TITLE
Slack invite expired

### ISSUE THREAD

**Issue by GatienC** [python-gsoc/python-gsoc.github.io#103]
Hi ! 
At the line 452 of index.html there is this invitation to the slack workspace :
https://join.slack.com/t/python-gsoc/shared_invite/enQtNDg0NDgwNjMyNTE2LTNlOGM1MWY2MzRlMjNhMGM2OWJjYzE3ODRmMmM0MjFjNGJmNGRiYzI4ZDc1ODgxOTYzMDQyNzBiNGFlYWVjZTY
but it is expired. Is it possible to get a new one please ?

Thanks !

**Comment by ucalyptus** [comment]
@GatienC Same here

**Comment by terriko** [comment]
Sorry, that was still last year's info.  We may not use slack in 2020 (we had some badness with the irc bridge we were using), so I've taken it off the page for now.
