### ISSUE TITLE
Update students page

### ISSUE THREAD

**Issue by sharmaadityaHQ** [python-gsoc/python-gsoc.github.io#131]
Update time commitment section on students page according to the changes made by Google for Google Summer of Code 2021.

Blog for reference - https://opensource.googleblog.com/2020/10/google-summer-of-code-2021-is-bringing.html

**Comment by jprankawat** [comment]
I would like to work on this issue.

**Comment by 4hund3rbird** [comment]
Please assign me this issue, I want to work on it.

**Comment by nrhitik** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by terriko** [comment]
The page is currently correct.  I don't know why this issue was still open.
