### ISSUE TITLE
python-gsoc blog page down?

### ISSUE THREAD

**Issue by scott-huberty** [python-gsoc/python-gsoc.github.io#148]
Hi, at least on my end it seems like the blogs page of the python-gsoc website is down. Can anyone else confirm?

![Screen Shot 2023-07-02 at 4 03 04 PM](https://github.com/python-gsoc/python-gsoc.github.io/assets/52462026/35db70bc-d984-436d-a8f5-7570c1fc4dee)

**Comment by botanicvelious** [comment]
fixed it apache decided to die...
