### ISSUE TITLE
A tiny tiny typo

### ISSUE THREAD

**Issue by vipulgupta2048** [python-gsoc/python-gsoc.github.io#84]
Hello, I was just reading through this amazing piece of documentation that I found while looking to contribute. It's beyond awesome. As a fellow documentation writer. I think it's great. While reading, I might have found this typo, hence I wanted to confirm in the offchance of me coming out as rude if I am not wrong. Hope, this is okay. 

https://github.com/python-gsoc/python-gsoc.github.io/blob/8ce4a83b090f953fc9128549260b2c826056bce6/students.html#L135

s/no do/nor do

https://github.com/python-gsoc/python-gsoc.github.io/blob/8ce4a83b090f953fc9128549260b2c826056bce6/mentors.html#L156

Following sentence case here, this probably would be `best at everything`.

**Comment by terriko** [comment]
The first one definitely looks like a typo.  The second was intentionally done for emphasis and can be left as is.  Feel free to send a pull request to fix that first one if you've got time, otherwise one of us will try to do it when we do!
