### ISSUE TITLE
Do not use debug=True on prodaction

### ISSUE THREAD

**Issue by VasiliyRusin** [python-gsoc/python-gsoc.github.io#88]
I suppose You use `debug=True` on this site. Check [this link](https://blogs.python-gsoc.org/en/yash-sharma/2018/07/09/using-asyncio-in-twisted/) to see error message.

**Comment by botanicvelious** [comment]
Ya we need to move a bunch from settings into a file that is loaded from a like config file not in the repo, same issue with the key
