### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-gsoc.github.io#92]
ui.js:40 Uncaught TypeError: Cannot set property 'onclick' of null
    at ui.js:40
    at ui.js:46

firefox 68.0.1 on loading homepage

**Comment by ayushiitr2901** [comment]
Hi, I am new contributing to Python, and this issue seems to be a good headstart.
If this issue is still open can I work on it, and can you help me with how I can start.

**Comment by botanicvelious** [comment]
Yes it still looks to be an issue, when you goto the mainpage at 

https://python-gsoc.org/

you will get an error 

TypeError: content is nullui.js:40:5
    <anonymous> https://python-gsoc.org/js/ui.js:40
    <anonymous> https://python-gsoc.org/js/ui.js:46

**Comment by sharmaaditya570191** [comment]
Hi @botanicvelious . Nice to see you after quite some time. I have submitted a PR which resolves this issue. Please have a look. Also please suggest if there are some issues under `python-gsoc` or `PSF` org on which I can currently work. Thanks.
